[[plugins]]
repo = 'Shougo/deoplete.nvim'
on_event = 'InsertCharPre'
hook_source = '''
  let g:deoplete#enable_at_startup = 1
  imap <expr><tab> pumvisible() ? "\<C-n>" : neosnippet#expandable_or_jumpable() ? "\<Plug>(neosnippet_expand_or_jump)" : "\<tab>"
  augroup MyVimrc
    autocmd InsertLeave,CompleteDone * if pumvisible() == 0 | pclose | endif
  augroup END
'''

[[plugins]]
repo = 'Shougo/neosnippet.vim'
on_event = 'InsertCharPre'
on_ft = [ 'snippet' ]
depends = [ 'neosnippet-snippets' ]
hook_source = '''
  imap <C-k> <Plug>(neosnippet_expand_or_jump)
  smap <C-k> <Plug>(neosnippet_expand_or_jump)
  xmap <C-k> <Plug>(neosnippet_expand_target)
  if has('conceal')
    set conceallevel=2 concealcursor=niv
  endif
'''

[[plugins]]
repo = 'Shougo/neosnippet-snippets'


# All in One
[[plugins]]
repo = 'fatih/vim-go'
on_ft = [ 'go' ]

[[plugins]]
repo = 'lervag/vimtex'
on_ft = [ 'tex' ]
hook_source = '''
  let g:tex_flavor = 'latex'
  let g:vimtex_compiler_latexmk_engines = { '_': '-pdfdvi' }
'''

# Auto-completion
[[plugins]]
repo = 'zchee/deoplete-go'
on_ft = [ 'go' ]

# Syntax Highlight
[[plugins]]
repo = 'octol/vim-cpp-enhanced-highlight'
on_ft = [ 'c', 'cpp' ]

[[plugins]]
repo = 'cespare/vim-toml'
on_ft = [ 'toml' ]

[[plugins]]
repo = 'othree/yajs.vim'
on_ft = [ 'javascript', 'javascriptreact' ]

[[plugins]]
repo = 'mxw/vim-jsx'
on_ft = [ 'javascriptreact' ]
hook_add = '''
  let g:jsx_ext_required = 1
'''

[[plugins]]
repo = 'HerringtonDarkholme/yats.vim'
on_ft = [ 'typescript', 'typescriptreact' ]

[[plugins]]
repo = 'peitalin/vim-jsx-typescript'
on_ft = [ 'typescriptreact' ]

[[plugins]]
repo = 'posva/vim-vue'
on_ft = [ 'vue' ]
hook_source = '''
  augroup MyVimrc
    autocmd FileType vue syntax sync fromstart
  augroup END
  setlocal iskeyword+=$
  setlocal iskeyword+=-
'''

[[plugins]]
repo = 'tomlion/vim-solidity'
on_ft = [ 'solidity' ]
